name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify README exists
        run: |
          test -f README.md && echo "README found ✅" || (echo "README.md missing ❌"; exit 1)


      - name: Hello CI
        run: echo "CI is set up and working!"
